### ISSUE TITLE
Playgound not working

### ISSUE THREAD

**Issue by teameh** [Neo4j-Swift/Neo4j-Swift#3]
The playgound looks very helpfull but it's not possible to execute the code because the `project.pbxproj` file is missing

<img width="420" alt="image" src="https://user-images.githubusercontent.com/1330668/69901079-ea89e700-137c-11ea-8481-fc91287d6243.png">

**Comment by niklassaers** [comment]
Sorry for not addressing this before. You need to run swift package generate-xcodeproj to get the .xcodeproj file with this version. Would it make sense to include a stock one? I'd like to avoid the problem of having it include a for most people nonsensical team. But perhaps that's better than not having the file at all?

**Comment by teameh** [comment]
No worries. I think you do not necessarily need to include it, as long as it's clear from the readme that you have to an can easily generate this yourself. That is currently not the case.

**Comment by teameh** [comment]
Ah I see you've already added the `.xcodeproj` project. Nice. 

However, I'm still not able to use the playground because the build is failing https://github.com/Neo4j-Swift/Neo4j-Swift/issues/8
