### ISSUE TITLE
SwiftPM can't resolve package

### ISSUE THREAD

**Issue by ValiHar** [Neo4j-Swift/Neo4j-Swift#4]
Hey there, 
it seems like there's an issue while resolving the dependency tree. Here's the error message:

> the package neo4j-swift[https://github.com/Neo4j-Swift/Neo4j-Swift] @ 5.0.0 contains incompatible dependencies:
>     bolt-swift[https://github.com/Neo4j-Swift/Bolt-swift.git] @ master

Would be nice if it gets fixed.

Thanks in advance, 
Valentin

**Comment by ValiHar** [comment]
Sorry, it's a duplicate.

**Comment by niklassaers** [comment]
Thanks Valentin, if you have the time to give the current development/non-blocking branch a spin, using the equivalent Bolt-Swift version, I'd appreciate feedback. Trying to coordinate its release with Vapor 4 and Swift 5.2
